---
# NOTE(dpawlik): There are some improvements done in Microshift 4.13 related
# to the systemd-resolved service, but after a test, for dnsmasq and Microshift 4.12,
# it is better when the dnsmasq service is deployed after the Microshift pods are
# running.
- name: Install DNSMasq
  become: true
  ansible.builtin.package:
    name: dnsmasq
    state: present
  notify: Disable dnsmasq service

# NOTE: The dnsmasq can be stopped, because the NetworkManager would spawn
# own instance of it and will respect its config.
- name: Copy dnsmasq configuration file to NetworkManager dir
  become: true
  ansible.builtin.copy:
    src: /etc/dnsmasq.conf
    dest: /etc/NetworkManager/dnsmasq.d/dnsmasq.conf
    remote_src: true
  notify:
    - Disable dnsmasq service
    - Reload NetworkManager

- name: Check if 99-cloud-init.conf exists
  become: true
  stat:
    path: /etc/NetworkManager/conf.d/99-cloud-init.conf
  register: _cloud_init_conf

- name: Comment 99-cloud-init.conf file
  become: true
  when: _cloud_init_conf.stat.exists
  copy:
    content: |
      ## Created by cloud-init on instance boot automatically, do not edit.
      ## \n\n# ANSIBLE: This file was commented by Ansible to enable dnsmasq functionality \n\n
      #[main]
      #dns = none
    path: /etc/NetworkManager/conf.d/99-cloud-init.conf

- name: Add information about new dnsmasq configuration file location
  become: true
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.conf
    insertbefore: '^# Configuration file for dnsmasq.'
    line: "\n\n# ANSIBLE: This file is now managed by NetworkManager - /etc/NetworkManager/dnsmasq.d/dnsmasq.conf\n\n"

- name: Change DNSMasq configuration file in NetworkManager
  become: true
  ansible.builtin.lineinfile:
    path: /etc/NetworkManager/dnsmasq.d/dnsmasq.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "^#server=/3.168.192.in-addr.arpa/10.1.2.3"
      line: "server={{ cloudprovider_dns | default(public_dns) | random }}"
    - regexp: '^# server=10.1.2.3@eth1'
      line: "server={{ public_dns | random}}"
    - regexp: "^interface=lo"
      line: "#interface=lo"
    - regexp: "^#address=\/double-click.net\/127.0.0.1"
      line: "address=/{{ fqdn }}/127.0.0.1"

- name: Get the LoadBalander ip address or Openshift Router ip address
  when: not microshift_frontend_address
  block:
    - name: Create script to get ingress ip address
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          IP=$(oc get svc -n openshift-ingress router-internal-default -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          if [ -z "${IP}" ]; then
              IP=$(oc get svc -n openshift-ingress router-internal-default -o jsonpath='{.spec.clusterIP}');
          fi
          echo "${IP}"
        dest: /tmp/recognize_ingress_ip.sh
        mode: 0755

    - name: Get Ingress IP Address
      ansible.builtin.command: /tmp/recognize_ingress_ip.sh
      register: _lb_ip

    - name: Set the LB or Router IP address as default address for FQDN
      ansible.builtin.set_fact:
        microshift_frontend_address: "{{ _lb_ip.stdout }}"

- name: Add new addresses to bind to the ingress
  become: true
  ansible.builtin.lineinfile:
    path: /etc/NetworkManager/dnsmasq.d/dnsmasq.conf
    line: "address=/{{ item }}/{{ microshift_frontend_address }}"
  loop: "{{ microshift_additional_addresses }}"
  when: microshift_frontend_address

- name: Add dnsmasq rule for NetworkManager
  become: true
  ansible.builtin.copy:
    content: |
      [main]
      dns=dnsmasq
    dest: /etc/NetworkManager/conf.d/00-microshift-use-dnsmasq.conf
  notify:
    - Disable dnsmasq service
    - Reload NetworkManager

- name: Flush handlers
  meta: flush_handlers
