---
- name: Check if pull-secret is provided when copr version is disabled
  ansible.builtin.fail:
    msg: "You need to provide pull-secret.txt content into the var!"
  when: not openshift_pull_secret and not use_copr_microshift

- name: Disable selinux
  ansible.builtin.include_tasks: selinux.yaml
  when: disable_selinux

- name: Setup Microshift repository
  ansible.builtin.include_tasks: repo.yaml

- name: Prepare host
  ansible.builtin.include_tasks: pre.yaml

- name: Disable swap
  ansible.builtin.include_tasks: swap.yaml
  when: disable_swap

- name: Setup tools
  ansible.builtin.include_tasks: tools.yaml
  when: setup_tools

- name: Prepare cri-o
  ansible.builtin.include_tasks: crio.yaml

- name: Prepare firewall
  ansible.builtin.include_tasks: firewall.yaml

- name: Use ramdisk for etcd service
  ansible.builtin.include_tasks: etcd_ramdisk.yaml
  when: etcd_on_ramdisk

- name: Setup Microshift
  ansible.builtin.include_tasks: microshift.yaml

- name: Provide credentials for restricted regitries
  ansible.builtin.include_tasks: registry_login.yaml
  when: not use_copr_microshift

- name: Verify that Microshift deployment is finished
  ansible.builtin.include_tasks: wait-for-microshift.yaml

- name: Create VG and LVM for openshift-storage topolvm
  ansible.builtin.include_tasks: openshift-storage.yaml

- name: Wait for the openshift-storage to be deployed
  ansible.builtin.include_tasks: wait-for-microshift.yaml

- name: Configure DNSMasq
  ansible.builtin.include_tasks: dnsmasq.yaml
  when: configure_dnsmasq

- name: Setup OLM
  ansible.builtin.include_tasks: olm.yaml
  when: setup_olm
