---
- name: Download official OLM script
  ansible.builtin.get_url:
    url: "https://github.com/operator-framework/operator-lifecycle-manager/releases/download/{{ olm_version }}/install.sh"
    dest: /tmp/olm-install.sh
    mode: "0755"

- name: Install OLM via official script
  ansible.builtin.shell: |
    /tmp/olm-install.sh {{ olm_version }}
