---
- name: Check if verify Microshift script exists
  ansible.builtin.stat:
    path: /usr/local/bin/wait-for-microshift.sh
  register: _script_exists

- name: Copy script to verify deployment
  become: true
  ansible.builtin.copy:
    src: wait-for-microshift.sh
    dest: /usr/local/bin/wait-for-microshift.sh
    mode: "0755"
  when: not _script_exists.stat.exists

- name: Check if all containers are up and ready
  ansible.builtin.command: /usr/local/bin/wait-for-microshift.sh
